/* Delete tables so we can create them */
DROP TABLE IF EXISTS login;

/* Create our tables */
CREATE TABLE login (id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 0) NOT NULL PRIMARY KEY,email  VARCHAR(200) NOT NULL,password VARCHAR(200) NOT NULL);

/* Insert data into login */
INSERT INTO login VALUES (1,'test_1@owasp.org','test_1');
INSERT INTO login VALUES (2,'test_2@owasp.org','test_2');
INSERT INTO login VALUES (3,'test_3@owasp.org','test_3');